/// Flutter icons RIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RIcon
///      fonts:
///       - asset: fonts/RIcon.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class RIcon {
  RIcon._();

  static const _kFontFam = 'RIcon';
  static const String? _kFontPkg = null;

  static const IconData laugh = IconData(0xf599, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
